version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: estherryu33/microservice-project:reverseproxy
  backend_user:
    build:
      context: ../../udagram-backend-user
    image: estherryu33/microservice-project:udagram-backend-user
  backend_feed:
    build:
      context: ../../udagram-backend-feed
    image: estherryu33/microservice-project:udagram-backend-feed
  frontend:
    build:
      context: ../../frontend
    image: estherryu33/microservice-project:udagram-frontend
